
name: 01 - Hello world

on: push

jobs: 
  premier-job:
    runs-on: ubuntu-latest

    steps: 
      - name: Dire bonjour
        run: echo  "Bonjour depuis Github actions ! "

      - name: Informations système
        run: |
          echo "Système d'exploitation : $(uname -s)"
          echo "version : $(uname -r)"
          echo "Utilisateur : $(whoami)"

      - name: Date et heure
        run: date
